### ISSUE TITLE
Provide a dynamic way to map properties

### ISSUE THREAD

**Issue by atomsfat** [gextech/binding-util#17]
Hi, 
I have been using this library and I think that it should be great adding support to map dynamically some properties.

For example
```groovy
   DomainDTO pojo = Util.bind(DomainDB, DomainDTO, ["tags"])
   pojo.tags = gson.parse(DomainDB.tags)
```
Could be rewritten to :
```groovy
 DomainDTO pojo = Util.bind(DomainDB, DomainDTO,  ["tags": {gson.parse(it)}])
```
Also if we can add a way to register this parses in order to @Autowired the binding-util.

What do you think about ?

**Comment by anallely** [comment]
:+1:  I like the idea.

**Comment by domix** [comment]
PR are welcome¡

**Comment by atomsfat** [comment]
Working done on #19
